image: python:3.7.6-alpine
stages:
  - test


e2e:remote:chrome:
  before_script:
    - pip3 install -r requirements.txt
  script:
    - pytest --local='false'
  services:
    - selenium/standalone-chrome:91.0-chromedriver-91.0
  tags:
    - to_dmz_stand

